const accountType = {
  GETALLACCOUNTS: "GETALLACCOUNTS",
  GETALLHOTELS: "GETALLHOTELS",
  GETALLPARTNERS: "GETALLPARTNERS",
  GETALLTYPES: "GETALLTYPES",
  ISLOGIN: "ISLOGIN",
  FALSELOGIN: "FALSELOGIN",
  ACCOUNTINFO: "ACCOUNTINFO",
  GETTOKEN: "GETTOKEN",
  GETALLRECOMMEND: "GETALLRECOMMEND",
  RECOMMEND: "RECOMMEND",
  MOVEOBJ: "MOVEOBJ",
  RESTAURANTS: "RESTAURANTS",
};
export default accountType;
